use_frameworks!

target 'shareViewUIActivityView_Example' do
    pod 'shareViewUIActivityView', :path => '../'
    
    target 'shareViewUIActivityView_Tests' do
        pod 'shareViewUIActivityView', :path => '../'
    end
end